export const CHECK_WINNER = "CHECK_WINNER";
export const CHANGE_TEMP_UNIT = "CHANGE_TEMP_UNIT";
export const GET_NEXT_CITIES = "GET_NEXT_CITIES";

export const FETCH_CITIES_START = "FETCHING_CITIES_START";
export const FETCH_CITIES_FAILURE = "FETCHING_CITIES_FAILURE"
export const FETCH_CITIES_ADD = "FETCHING_CITIES_ADD";
