export const CHECK_IS_CITY_HOTTEST = "CHECK_IS_CITY_HOTTEST";
export const CHANGE_TEMP_UNIT = "CHANGE_TEMP_UNIT";
export const GET_NEXT_CITIES = "GET_NEXT_CITIES";
export const START_FETCHING_CITIES = "START_FETCHING_CITIES";
export const ADD_FETCHED_CITIES = "ADD_FETCHED_CITIES";
